dist: trusty
language: rust
cache:
  directories:
    - ~/.cargo
rust:
  - stable
os:
  - linux
  - osx
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo update
  - cargo fmt --all -- --write-mode=diff
  - cargo test
