dist: trusty
language: rust
cache: cargo
rust:
  - stable
os:
  - linux
  - osx
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo update
  - cargo fmt --all -- --write-mode=diff
  - RUST_BACKTRACE=1 cargo test
