dist: trusty
language: rust
cache: cargo
rust:
  - stable
os:
  - linux
  - osx
branches:
  only:
    - master
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo update
  - cargo fmt --all -- --write-mode=diff
  - cargo test
