[package]
name = "blackfynn"
version = "0.1.14"
authors = ["Blackfynn <https://github.com/Blackfynn/blackfynn-rust>"]
publish = false

[dependencies]
chrono = { version = "^0.4", features = ["serde"] }
futures = "^0.1"
hyper = "^0.11"
hyper-tls = "^0.1"
lazy_static = "^1.0"
rusoto_core = "^0.32"
rusoto_credential = "^0.11"
rusoto_s3 = "^0.32"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
tokio-core = "^0.1"
url = "^1.6"